// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "golang-foo": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/vikram-raj/app-jan-30-1/design
// --out=$(GOPATH)/src/github.com/vikram-raj/app-jan-30-1
// --version=v1.3.0

package app

// StatusHref returns the resource href.
func StatusHref() string {
	return "/api/status"
}
